### ISSUE TITLE
`crc status -w` during start can result in a panic of the command

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc#3743]
when you do:

```
$ ./crc status -w
```

and start the cluster in another terminal, the command might fail:

```
./crc status -w                                           1 
CRC VM:          Running
MicroShift:      Unreachable (v4.13.3)
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     35.05GB
Cache Directory: /home/gbraad/.crc/cache
RAM: -1 B ?%  [██████████████████████████████████████████████████████████████████████████████████████████████████████] 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/crc-org/crc/cmd/crc/cmd.runWatchStatus({0x23bb7c0, 0xc000014018}, 0xc00090bb60, {0xc000056cf0?, 0xc0009185b8?})
	/builddir/build/BUILD/crc-2.22.1/cmd/crc/cmd/status.go:104 +0x2a5
github.com/crc-org/crc/cmd/crc/cmd.runStatus({0x23bb7c0?, 0xc000014018?}, 0xc0001e72d0?, {0xc000056cf0?, 0x0?}, {0x0?, 0xc00081fc38?}, 0xd7?)
	/builddir/build/BUILD/crc-2.22.1/cmd/crc/cmd/status.go:59 +0x36
github.com/crc-org/crc/cmd/crc/cmd.glob..func12(0xc0000d6000?, {0x5?, 0x2041ebf?, 0xc?})
	/builddir/build/BUILD/crc-2.22.1/cmd/crc/cmd/status.go:37 +0x53
github.com/crc-org/crc/cmd/crc/cmd.executeWithLogging.func1(0x35a50c0, {0xc000940650, 0x0, 0x1})
	/builddir/build/BUILD/crc-2.22.1/cmd/crc/cmd/root.go:170 +0x102
github.com/spf13/cobra.(*Command).execute(0x35a50c0, {0xc000940630, 0x1, 0x1})
	/builddir/build/BUILD/crc-2.22.1/vendor/github.com/spf13/cobra/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x35a67c0)
	/builddir/build/BUILD/crc-2.22.1/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/crc-2.22.1/vendor/github.com/spf13/cobra/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/builddir/build/BUILD/crc-2.22.1/vendor/github.com/spf13/cobra/command.go:961
github.com/crc-org/crc/cmd/crc/cmd.Execute()
	/builddir/build/BUILD/crc-2.22.1/cmd/crc/cmd/root.go:105 +0xd9
main.main()
	/builddir/build/BUILD/crc-2.22.1/cmd/crc/main.go:8 +0x17
```

![Screenshot from 2023-06-29 13-59-49](https://github.com/crc-org/crc/assets/1894/90e4454a-9ea5-4c37-99e4-df94a7bfb7af)

**Comment by anjannath** [comment]
@gbraad this was fixed i believe and can be closed?

**Comment by gbraad** [comment]
Which PR fixed this? I believe Christophe mentioned this

**Comment by anjannath** [comment]
my bad, i thought the original PR already addressed this, but tried the steps to reproduce again and it is reproducible

**Comment by cfergeau** [comment]
This code was changed, but the bug probably still occurs.
The code crashes at `cpuBars[i].SetCurrent(cpuLoad)`

Looking at https://github.com/crc-org/crc/blob/6b61c2ff0e23d92ec886bbc88205378b28cc80f3/cmd/crc/cmd/status.go#L81-L100, we create the `cpuBars` array once, and it has the same length as `loadResult.CPUUse`.
I think what happens is that `len(loadResult.CPUUse)` changes over time, maybe it's 0 when there is no VM running, and it becomes `$vm_cpu_count` while the VM is running? In which case `loadResult.CPUUse` would have more items than `cpuBars`, and this would cause this panic.
Maybe the `isPullInit` check should be comparing `len(loadResult.CPUUse)` and `len(cpuBars)`?
